# Site Settings
title: Hackeando Salud
email: info@hackeandosalud.cl
description: >
  Mejorando la salud 1 bit a la vez
baseurl: "/startjekyll"
url: "http://hackeandosalud.github.io"
twitter_username: hackeandosalud
github_username:  hackeandosalud
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM